// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pballok/gurps-bchest-be/internal/character"
	"github.com/pballok/gurps-bchest-be/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorable creates a new instance of MockStorable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorable[K comparable, V any, F any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorable[K, V, F] {
	mock := &MockStorable[K, V, F]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorable is an autogenerated mock type for the Storable type
type MockStorable[K comparable, V any, F any] struct {
	mock.Mock
}

type MockStorable_Expecter[K comparable, V any, F any] struct {
	mock *mock.Mock
}

func (_m *MockStorable[K, V, F]) EXPECT() *MockStorable_Expecter[K, V, F] {
	return &MockStorable_Expecter[K, V, F]{mock: &_m.Mock}
}

// Add provides a mock function for the type MockStorable
func (_mock *MockStorable[K, V, F]) Add(ctx context.Context, item V) (K, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 K
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, V) (K, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, V) K); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(K)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, V) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorable_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockStorable_Add_Call[K comparable, V any, F any] struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx
//   - item
func (_e *MockStorable_Expecter[K, V, F]) Add(ctx interface{}, item interface{}) *MockStorable_Add_Call[K, V, F] {
	return &MockStorable_Add_Call[K, V, F]{Call: _e.mock.On("Add", ctx, item)}
}

func (_c *MockStorable_Add_Call[K, V, F]) Run(run func(ctx context.Context, item V)) *MockStorable_Add_Call[K, V, F] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(V))
	})
	return _c
}

func (_c *MockStorable_Add_Call[K, V, F]) Return(v K, err error) *MockStorable_Add_Call[K, V, F] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStorable_Add_Call[K, V, F]) RunAndReturn(run func(ctx context.Context, item V) (K, error)) *MockStorable_Add_Call[K, V, F] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStorable
func (_mock *MockStorable[K, V, F]) Delete(ctx context.Context, id K) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, K) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorable_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorable_Delete_Call[K comparable, V any, F any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStorable_Expecter[K, V, F]) Delete(ctx interface{}, id interface{}) *MockStorable_Delete_Call[K, V, F] {
	return &MockStorable_Delete_Call[K, V, F]{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockStorable_Delete_Call[K, V, F]) Run(run func(ctx context.Context, id K)) *MockStorable_Delete_Call[K, V, F] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(K))
	})
	return _c
}

func (_c *MockStorable_Delete_Call[K, V, F]) Return(err error) *MockStorable_Delete_Call[K, V, F] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorable_Delete_Call[K, V, F]) RunAndReturn(run func(ctx context.Context, id K) error) *MockStorable_Delete_Call[K, V, F] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStorable
func (_mock *MockStorable[K, V, F]) Get(ctx context.Context, id K) (V, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, K) (V, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, K) V); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, K) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorable_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorable_Get_Call[K comparable, V any, F any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStorable_Expecter[K, V, F]) Get(ctx interface{}, id interface{}) *MockStorable_Get_Call[K, V, F] {
	return &MockStorable_Get_Call[K, V, F]{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockStorable_Get_Call[K, V, F]) Run(run func(ctx context.Context, id K)) *MockStorable_Get_Call[K, V, F] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(K))
	})
	return _c
}

func (_c *MockStorable_Get_Call[K, V, F]) Return(v V, err error) *MockStorable_Get_Call[K, V, F] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStorable_Get_Call[K, V, F]) RunAndReturn(run func(ctx context.Context, id K) (V, error)) *MockStorable_Get_Call[K, V, F] {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStorable
func (_mock *MockStorable[K, V, F]) List(ctx context.Context, filters F) ([]V, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []V
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, F) ([]V, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, F) []V); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, F) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorable_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorable_List_Call[K comparable, V any, F any] struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx
//   - filters
func (_e *MockStorable_Expecter[K, V, F]) List(ctx interface{}, filters interface{}) *MockStorable_List_Call[K, V, F] {
	return &MockStorable_List_Call[K, V, F]{Call: _e.mock.On("List", ctx, filters)}
}

func (_c *MockStorable_List_Call[K, V, F]) Run(run func(ctx context.Context, filters F)) *MockStorable_List_Call[K, V, F] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(F))
	})
	return _c
}

func (_c *MockStorable_List_Call[K, V, F]) Return(vs []V, err error) *MockStorable_List_Call[K, V, F] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockStorable_List_Call[K, V, F]) RunAndReturn(run func(ctx context.Context, filters F) ([]V, error)) *MockStorable_List_Call[K, V, F] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStorable
func (_mock *MockStorable[K, V, F]) Update(ctx context.Context, id K, item V) error {
	ret := _mock.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, K, V) error); ok {
		r0 = returnFunc(ctx, id, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorable_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorable_Update_Call[K comparable, V any, F any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx
//   - id
//   - item
func (_e *MockStorable_Expecter[K, V, F]) Update(ctx interface{}, id interface{}, item interface{}) *MockStorable_Update_Call[K, V, F] {
	return &MockStorable_Update_Call[K, V, F]{Call: _e.mock.On("Update", ctx, id, item)}
}

func (_c *MockStorable_Update_Call[K, V, F]) Run(run func(ctx context.Context, id K, item V)) *MockStorable_Update_Call[K, V, F] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(K), args[2].(V))
	})
	return _c
}

func (_c *MockStorable_Update_Call[K, V, F]) Return(err error) *MockStorable_Update_Call[K, V, F] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorable_Update_Call[K, V, F]) RunAndReturn(run func(ctx context.Context, id K, item V) error) *MockStorable_Update_Call[K, V, F] {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Characters provides a mock function for the type MockStorage
func (_mock *MockStorage) Characters() storage.Storable[storage.CharacterKeyType, character.Character, storage.CharacterFilterType] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Characters")
	}

	var r0 storage.Storable[storage.CharacterKeyType, character.Character, storage.CharacterFilterType]
	if returnFunc, ok := ret.Get(0).(func() storage.Storable[storage.CharacterKeyType, character.Character, storage.CharacterFilterType]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.Storable[storage.CharacterKeyType, character.Character, storage.CharacterFilterType])
		}
	}
	return r0
}

// MockStorage_Characters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Characters'
type MockStorage_Characters_Call struct {
	*mock.Call
}

// Characters is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Characters() *MockStorage_Characters_Call {
	return &MockStorage_Characters_Call{Call: _e.mock.On("Characters")}
}

func (_c *MockStorage_Characters_Call) Run(run func()) *MockStorage_Characters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Characters_Call) Return(storable storage.Storable[storage.CharacterKeyType, character.Character, storage.CharacterFilterType]) *MockStorage_Characters_Call {
	_c.Call.Return(storable)
	return _c
}

func (_c *MockStorage_Characters_Call) RunAndReturn(run func() storage.Storable[storage.CharacterKeyType, character.Character, storage.CharacterFilterType]) *MockStorage_Characters_Call {
	_c.Call.Return(run)
	return _c
}
