all: false
dir: "internal/mocks"
filename: "{{.SrcPackageName}}_mocks.go"
pkgname: "mocks"
template: testify
packages:
  github.com/pballok/gurps-bchest-be/internal/storage:
    interfaces:
      Storable:
      Storage:
  github.com/pballok/gurps-bchest-be/internal/character:
    interfaces:
      Character:
