with-expecter: True
dir: "internal/mocks/{{.PackageName}}"
outpkg: "mocks"
packages:
  github.com/pballok/gurps-bchest-be/internal/memstorage:
    config:
    interfaces:
      fileSystem:
        config:
