// Code generated by mockery v2.46.3. DO NOT EDIT.

package storage

import (
	character "github.com/pballok/gurps-bchest-be/internal/character"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Characters provides a mock function with given fields:
func (_m *MockStorage) Characters() Storable[CharacterKeyType, character.Character, CharacterFilterType] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Characters")
	}

	var r0 Storable[CharacterKeyType, character.Character, CharacterFilterType]
	if rf, ok := ret.Get(0).(func() Storable[CharacterKeyType, character.Character, CharacterFilterType]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Storable[CharacterKeyType, character.Character, CharacterFilterType])
		}
	}

	return r0
}

// MockStorage_Characters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Characters'
type MockStorage_Characters_Call struct {
	*mock.Call
}

// Characters is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Characters() *MockStorage_Characters_Call {
	return &MockStorage_Characters_Call{Call: _e.mock.On("Characters")}
}

func (_c *MockStorage_Characters_Call) Run(run func()) *MockStorage_Characters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Characters_Call) Return(_a0 Storable[CharacterKeyType, character.Character, CharacterFilterType]) *MockStorage_Characters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Characters_Call) RunAndReturn(run func() Storable[CharacterKeyType, character.Character, CharacterFilterType]) *MockStorage_Characters_Call {
	_c.Call.Return(run)
	return _c
}

// ImportData provides a mock function with given fields: _a0
func (_m *MockStorage) ImportData(_a0 string) {
	_m.Called(_a0)
}

// MockStorage_ImportData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportData'
type MockStorage_ImportData_Call struct {
	*mock.Call
}

// ImportData is a helper method to define mock.On call
//   - _a0 string
func (_e *MockStorage_Expecter) ImportData(_a0 interface{}) *MockStorage_ImportData_Call {
	return &MockStorage_ImportData_Call{Call: _e.mock.On("ImportData", _a0)}
}

func (_c *MockStorage_ImportData_Call) Run(run func(_a0 string)) *MockStorage_ImportData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_ImportData_Call) Return() *MockStorage_ImportData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_ImportData_Call) RunAndReturn(run func(string)) *MockStorage_ImportData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
